### ISSUE TITLE
Non working docker build instructions in README.md

### ISSUE THREAD

**Issue by sandrobonazzola** [arcalot/arcalog#5]
## Describe the bug

`README.md` says:
> You can also use the provided Dockerfile, as long as you provide a default `config.yaml`. If you would like to use a custom path to a YAML-formatted file via the `--config` flag, e.g.: `arcalog --config /path/to/config.yaml`, you will have to mount the config file into the container as well.
> 
> ```bash
> docker build -t arcalog .
> docker run -v /path/to/datafolder:/data arcalog
> ```

But executing in shell I get:

```console
$ docker build -t arcalog 
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Error: no context directory and no Containerfile specified
```

## To reproduce

Blindly follow `README.md`

## Additional context

```console
$ docker --version
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
podman version 4.1.1
```

**Comment by ghost** [comment]
Did you use `docker build -t arcalog` or `docker build -t arcalog .`?

**Comment by sandrobonazzola** [comment]
completely missed the trailing `.` closing.
