### ISSUE TITLE
 code: 2, kind: NotFound, message: "No such file or directory"

### ISSUE THREAD

**Issue by jtaleric** [arcalot/arcalog#6]
## Describe the bug
After collecting prow data, I tried to view via the http server, but was faced with 

```thread 'tokio-runtime-worker' panicked at 'The data has not been gathered to and cannot be read from data/prow/artifacts/1572175581204713472/prow/failure: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/jtaleric/dev/arcalog/src/system.rs:25:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'The data has not been gathered to and cannot be read from data/prow/artifacts/1572175581204713472/prow/failure: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/jtaleric/dev/arcalog/src/system.rs:25:43
thread 'tokio-runtime-worker' panicked at 'The data has not been gathered to and cannot be read from data/prow/artifacts/1572175581204713472/prow/failure: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/jtaleric/dev/arcalog/src/system.rs:25:43
```

## To reproduce

`$ arcalog --collect prow`
`$ arcalog --http`

Search for a known build id.

## Additional context
I am not running in a container, so i am wondering if the full path is causing the issue?

**Comment by ghost** [comment]
Thanks for reporting. This bug was found yesterday by another user as well, fix incoming shortly.

**Comment by ghost** [comment]
This should be fixed now - sorry about that, didn't catch the error as we still need a CI (oh, the irony!) and it "worked on my laptop". 😉 

Let me know if it's still not fixed for you. Currently, there is no separation of matches between failures and successes as the identification step still needs to be implemented. This means that in some cases, you might end up with 30k+ error messages per job, where 29,900 of them also occur in successful jobs (arbitrary numbers taken as example).

The next steps prior to a visualization are the separation and removal of matches, then using the failure-related corpus with NLP for proper lemmatization. Contributions and questions are very welcome (e.g. via [Discussions](https://github.com/orgs/arcalot/discussions)).
